In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import os
import tensorflow as tf

In [2]:
df = pd.read_csv(r"C:\Users\admin\Desktop\Door-Detection\Door-Detection\dataset_289_samples_final_3am.csv")

In [3]:
df

Type  Distance0  Distance1  Distance2  Distance3  Distance4  Distance5  \
0       0        178        114        179         97         67        130   
1       0        179        176        178         33         24         96   
2       1         86         86         86         83         68         86   
3       1         99        100         99         80         98         93   
4       1         70         70         69         64         68         58   
..    ...        ...        ...        ...        ...        ...        ...   
283     0        357        192          7          7          7         90   
284     0          7          7          7          7          7          7   
285     0        116          7        115         89         98          7   
286     0         51         51         51          8         38         51   
287     0         42         42         42          7          7          8   

     Distance6  Distance7  Distance8  ...  Distance80  Distance81  Distance82  \
0           73        132         93  ...          92          89          90   
1           62        103         75  ...          90          84          90   
2           60         85         86  ...          57          76          76   
3           64         94         98  ...          87          68         117   
4            7         70         69  ...         103         132          74   
..         ...        ...        ...  ...         ...         ...         ...   
283        108          6          7  ...           7           7           9   
284          7          8          8  ...           7           7           7   
285          6          7        103  ...           6           7           7   
286         51          6          8  ...           8           9           7   
287          8          6          8  ...           7           7           9   

     Distance83  Distance84  Distance85  Distance86  Distance87  Distance88  \
0            57          54          48          68          89          89   
1            89          63          51          88          90          85   
2            72          76           7          53          64          76   
3            97         120         119          73          80         119   
4            72          65          58          72          55          71   
..          ...         ...         ...         ...         ...         ...   
283           7           7           7           7           7           7   
284           7           7           6           7           9           6   
285           9           9           7           7           7           8   
286           7           7           7           9           9           7   
287           7           7           7           7           7           7   

     Distance89  
0          61.0  
1          74.0  
2          77.0  
3          62.0  
4          69.0  
..          ...  
283         7.0  
284         7.0  
285         7.0  
286         7.0  
287         7.0  

[288 rows x 91 columns]

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 91 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Type        288 non-null    int64  
 1   Distance0   288 non-null    int64  
 2   Distance1   288 non-null    int64  
 3   Distance2   288 non-null    int64  
 4   Distance3   288 non-null    int64  
 5   Distance4   288 non-null    int64  
 6   Distance5   288 non-null    int64  
 7   Distance6   288 non-null    int64  
 8   Distance7   288 non-null    int64  
 9   Distance8   288 non-null    int64  
 10  Distance9   288 non-null    int64  
 11  Distance10  288 non-null    int64  
 12  Distance11  288 non-null    int64  
 13  Distance12  288 non-null    int64  
 14  Distance13  288 non-null    int64  
 15  Distance14  288 non-null    int64  
 16  Distance15  288 non-null    int64  
 17  Distance16  288 non-null    int64  
 18  Distance17  288 non-null    int64  
 19  Distance18  288 non-null    i

In [4]:
df.describe()

Type   Distance0   Distance1   Distance2   Distance3   Distance4  \
count  288.000000  288.000000  288.000000  288.000000  288.000000  288.000000   
mean     0.524306  109.055556   99.204861   95.829861   48.965278   48.302083   
std      0.500278   78.840975   66.444625   61.873330   36.720797   40.261632   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000   60.000000   58.500000   59.000000    7.750000    7.000000   
50%      1.000000   93.000000   90.000000   83.500000   54.000000   51.000000   
75%      1.000000  137.000000  127.250000  121.250000   82.000000   75.250000   
max      1.000000  357.000000  357.000000  335.000000  161.000000  182.000000   

        Distance5   Distance6   Distance7   Distance8  ...  Distance80  \
count  288.000000  288.000000  288.000000  288.000000  ...  288.000000   
mean    46.833333   39.135417   41.434028   65.809028  ...   39.538194   
std     40.052666   32.076331   45.154120   47.830220  ...   44.957029   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      7.000000    7.000000    7.000000    9.000000  ...    7.000000   
50%     53.500000   44.000000   13.000000   66.500000  ...    8.000000   
75%     75.000000   62.000000   63.250000   96.250000  ...   70.250000   
max    168.000000  143.000000  296.000000  292.000000  ...  217.000000   

       Distance81  Distance82  Distance83  Distance84  Distance85  Distance86  \
count  288.000000  288.000000  288.000000  288.000000  288.000000  288.000000   
mean    29.284722   35.100694   42.006944   47.836806   39.031250   29.625000   
std     32.836765   39.742029   42.463839   45.761361   56.471346   31.740317   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      7.000000    7.000000    8.000000    8.000000    7.000000    7.000000   
50%      8.000000    8.000000    9.000000   21.000000    8.000000    8.000000   
75%     51.000000   64.250000   76.000000   84.000000   68.000000   55.000000   
max    133.000000  243.000000  213.000000  197.000000  777.000000  175.000000   

       Distance87  Distance88  Distance89  
count  288.000000  288.000000  287.000000  
mean    27.548611   47.718750   24.303136  
std     29.549894   47.941174   28.374779  
min      0.000000    0.000000    0.000000  
25%      7.000000    7.000000    7.000000  
50%      8.000000    9.000000    8.000000  
75%     52.250000   80.500000   47.500000  
max    137.000000  251.000000  146.000000  

[8 rows x 91 columns]

In [5]:
df = df.sample(frac=1).reset_index(drop=True)
df

Type  Distance0  Distance1  Distance2  Distance3  Distance4  Distance5  \
0       1        126        127        129         82         35          7   
1       1         79         79         79         78          8          7   
2       0        348        172        141          7          7        142   
3       1         95         95         96         74         94         55   
4       1         81         81         59         58         57          7   
..    ...        ...        ...        ...        ...        ...        ...   
283     0          6          6        286         87          5          5   
284     1         61         61         61         61         51         37   
285     1         62         62         62         52         51         63   
286     1         72         73         72         72         72         71   
287     1        124        129        133         73        122         64   

     Distance6  Distance7  Distance8  ...  Distance80  Distance81  Distance82  \
0           56          7        122  ...           8          47          93   
1            7         49         77  ...          67          63           7   
2            7          7        173  ...           8           8           8   
3            7          7         94  ...          92           7          51   
4           50          7         59  ...         140          81         126   
..         ...        ...        ...  ...         ...         ...         ...   
283          6          7          9  ...           8           8           8   
284          9          7         61  ...         101           7           8   
285         52          7         61  ...           7          52          55   
286         54          6         58  ...          96          62           7   
287         88         84        116  ...          18          16           7   

     Distance83  Distance84  Distance85  Distance86  Distance87  Distance88  \
0            94          94          94           8           8           8   
1            68          68          68           7           7          68   
2           112           8           8           9         110           8   
3            83          87           7          86           8         182   
4            75          80          53          71          79         125   
..          ...         ...         ...         ...         ...         ...   
283           8           8          58         137           7           8   
284         101         100           7          81          81           8   
285          93          91          61          60           7           8   
286          95           8          85          95          46           8   
287           7          14           7          14          13           8   

     Distance89  
0          47.0  
1          69.0  
2           8.0  
3           6.0  
4          53.0  
..          ...  
283         8.0  
284        70.0  
285         8.0  
286         6.0  
287        13.0  

[288 rows x 91 columns]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop('Type', axis = 1).values
y = df['Type'].values

In [8]:
X

array([[126., 127., 129., ...,   8.,   8.,  47.],
       [ 79.,  79.,  79., ...,   7.,  68.,  69.],
       [348., 172., 141., ..., 110.,   8.,   8.],
       ...,
       [ 62.,  62.,  62., ...,   7.,   8.,   8.],
       [ 72.,  73.,  72., ...,  46.,   8.,   6.],
       [124., 129., 133., ...,  13.,   8.,  13.]])

In [9]:
y

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1], dtype=int64)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 101)

In [11]:
print("Shape of X_train = ", X_train.shape)
print("Shape of y_train = ", y_train.shape)
print("Shape of X_test = ", X_test.shape)
print("Shape of y_test = ", y_test.shape)

Shape of X_train =  (216, 90)
Shape of y_train =  (216,)
Shape of X_test =  (72, 90)
Shape of y_test =  (72,)


In [12]:
X_test

array([[ 52.,  52.,  53., ...,  39.,  36.,  36.],
       [163., 162., 164., ...,   6., 150.,   8.],
       [109., 109., 106., ...,   8.,  54.,   8.],
       ...,
       [154., 127., 128., ...,   9.,   6.,   7.],
       [357., 242., 146., ...,   8.,   7.,   8.],
       [ 57.,  57.,  56., ...,   7.,   6.,   8.]])

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler = MinMaxScaler()

In [15]:
scaler.fit(X_train)
X_train = scaler.transform(X_train)

In [16]:
X_test = scaler.transform(X_test)

In [17]:
X_train

array([[0.20168067, 0.20168067, 0.21791045, ..., 0.59124088, 0.33864542,
        0.55479452],
       [0.01960784, 0.01960784, 0.02089552, ..., 0.05109489, 0.02788845,
        0.06164384],
       [0.28011204, 0.28011204, 0.29850746, ..., 0.37226277, 0.20717131,
        0.35616438],
       ...,
       [0.17647059, 0.17647059, 0.1880597 , ..., 0.05109489, 0.03187251,
        0.04794521],
       [0.38655462, 0.37815126, 0.41492537, ..., 0.71532847, 0.02788845,
        0.04794521],
       [0.6442577 , 0.62464986, 0.46865672, ..., 0.06569343, 0.02788845,
        0.04794521]])

In [18]:
y_train

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0], dtype=int64)

In [19]:
X_test

array([[0.14565826, 0.14565826, 0.15820896, ..., 0.28467153, 0.14342629,
        0.24657534],
       [0.45658263, 0.45378151, 0.48955224, ..., 0.04379562, 0.59760956,
        0.05479452],
       [0.30532213, 0.30532213, 0.31641791, ..., 0.05839416, 0.21513944,
        0.05479452],
       ...,
       [0.43137255, 0.3557423 , 0.38208955, ..., 0.06569343, 0.02390438,
        0.04794521],
       [1.        , 0.67787115, 0.4358209 , ..., 0.05839416, 0.02788845,
        0.05479452],
       [0.15966387, 0.15966387, 0.16716418, ..., 0.05109489, 0.02390438,
        0.05479452]])

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
logmodel = LogisticRegression()

In [22]:
logmodel.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').